version: '3'

services:

  node:
    build: . 
    container_name: react-simple-chatbot
    ports:
      - "3003:8080"    
    volumes:
      - '.:/app'
      - '/app/node_modules'      
    command: sh -c "npm start"